version: '3.7'

services:


  pace-sso:
    container_name: pace-sso
    build: ./SSO
    # image: assetguard_web
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - ./SSO/:/usr/src/app/
      # - //AssetGuard/app:/usr/src/app/
    ports:
      - 8003:8003
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - pace_core_core-net


  db:
    image: postgres:12.0-alpine
    volumes:
     - postgresData:/var/lib/postgresql/data/
      # - ./SSO/db_data:/var/lib/postgresql/data/
      # - ./pgdata:/var/lib/postgresql/data
    #  - /var/lib/postgresql/data
    # command: initdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev321
      - POSTGRES_DB=pace
    networks:
      - pace_core_core-net
      # - PGDATA="/var/lib/postgresql/data/postgres_data"

  # frontend:
  #   container_name: sso_frontend
  #   build: ./sso_frontend
  #   # image: react-docker
  #   volumes:
  #       - ./sso_frontend:/usr/src/app:rw
  #   ports:
  #     - "8080:8080"
  #   stdin_open: true
  #   tty: true

  pgadmin:
    image: dpage/pgadmin4
    links:
      - db
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: virajk@teknobuilt.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/root/.pgadmin
      - pg4volume:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pace_core_core-net
   
  redis:
    image: "redis:alpine"
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 3000:3000
  #   volumes:
  #       - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
  #       - ./sso_frontend:/usr/src/app
  #   depends_on:
  #     # - pace_sso
  #     - frontend


  # mongodb:
  #   image: mongo
  #   container_name: mongo_db
  #   restart: always
  #   # volumes:
  #   #   - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
  #   # environment:
  #     # - MONGO_INITDB_ROOT_USERNAME: root
  #     # - MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27018:27018
  #   command: mongod

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8082:8082
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_SERVER: mongo_db
  #   depends_on:
  #     - mongodb

volumes:
  postgresData:
    driver : local
  pgadmin:
  pg4volume:

networks:
  pace_core_core-net:
    external: true
    
