# Generated by Django 3.0.4 on 2021-07-20 04:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20210720_0438'),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('applications', '0004_apphostings_fkoauthclientid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apphostings',
            unique_together={('fkAppId', 'fkCompanyId', 'fkOauthClientId', 'appDomain')},
        ),
    ]
