# Generated by Django 3.0.4 on 2021-07-22 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20210720_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('moduleCode', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True, help_text='Flag for status of hosting')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Created date of User invitation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='last updated date of invitaion')),
                ('fkAppId', models.ForeignKey(default=None, help_text='Application to which user wants to subscribe', on_delete=django.db.models.deletion.CASCADE, to='applications.Applications', verbose_name='App Id')),
            ],
            options={
                'verbose_name_plural': 'Application Modules',
            },
        ),
    ]
