# Generated by Django 3.0.4 on 2021-07-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='targetPage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='moduleCode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='modules',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
