# Generated by Django 3.0.4 on 2021-09-11 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('applications', '0007_auto_20210723_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='apphostings',
            name='apiDomain',
            field=models.CharField(blank=True, default='', help_text='API domain URL', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='apphostings',
            name='appDomain',
            field=models.CharField(default=None, help_text='App domain URL', max_length=256),
        ),
        migrations.AlterField(
            model_name='apphostings',
            name='fkOauthClientId',
            field=models.ForeignKey(blank=True, default=None, help_text='OAuth ClientID to be selected/mentioned', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
