# Generated by Django 3.0.4 on 2021-09-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20210911_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apphostings',
            name='apiDomain',
            field=models.CharField(blank=True, default='', help_text='API domain URL', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='apphostings',
            name='appDomain',
            field=models.CharField(blank=True, default=None, help_text='App domain URL', max_length=256, null=True),
        ),
    ]
