# Generated by Django 3.0.4 on 2022-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_modules_moduleicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='targetPage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
