# Generated by Django 3.0.4 on 2021-07-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210713_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='departmentDescription',
            field=models.CharField(default=' ', help_text='Name for prescription details', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='departmentName',
            field=models.CharField(default=' ', help_text='Name for departments', max_length=100),
        ),
    ]
