# Generated by Django 3.0.4 on 2021-07-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20210720_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='primaryNumber',
            field=models.CharField(blank=True, help_text='Primary Number for SOS', max_length=30, null=True, verbose_name='Primary Number'),
        ),
        migrations.AddField(
            model_name='projects',
            name='secondaryNumber',
            field=models.CharField(blank=True, help_text='Secondary Number for SOS', max_length=30, null=True, verbose_name='Secondary Number'),
        ),
    ]
