# Generated by Django 3.0.4 on 2021-09-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20210723_1131'),
        ('companies', '0006_companies_isadconfigured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Status of subscription')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('fkAppId', models.ForeignKey(help_text='application details', on_delete=django.db.models.deletion.CASCADE, to='applications.Applications', verbose_name='Company ID')),
                ('fkCompanyId', models.ForeignKey(help_text='company details', on_delete=django.db.models.deletion.CASCADE, to='companies.Companies', verbose_name='Company ID')),
                ('fkModuleId', models.ForeignKey(help_text='module details', on_delete=django.db.models.deletion.CASCADE, to='applications.Modules', verbose_name='Company ID')),
            ],
        ),
    ]
