# Generated by Django 3.0.4 on 2021-09-11 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20210911_0915'),
        ('companies', '0007_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='fkAppId',
            field=models.ForeignKey(help_text='application details', on_delete=django.db.models.deletion.CASCADE, to='applications.Applications', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='fkCompanyId',
            field=models.ForeignKey(help_text='company details', on_delete=django.db.models.deletion.CASCADE, to='companies.Companies', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='fkModuleId',
            field=models.ForeignKey(help_text='module details', on_delete=django.db.models.deletion.CASCADE, to='applications.Modules', verbose_name='Module'),
        ),
    ]
