# Generated by Django 3.0.4 on 2021-10-19 09:54

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20210911_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='primaryNumber',
            field=models.CharField(default='0987654321', help_text='Primary Number for SOS', max_length=30, verbose_name='Primary Number'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectImage',
            field=models.ImageField(blank=True, help_text='Logo file for Projects', null=True, upload_to=companies.models.updateProjectFilename, verbose_name='Projects Image'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectNature',
            field=models.CharField(default='oil & gas corporation', help_text='Natures of a projects', max_length=100, verbose_name='Projects Natures'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectPhase',
            field=models.CharField(default='Development', help_text='Phases of a projects', max_length=100, verbose_name='Projects Phases'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='publish',
            field=models.BooleanField(default='True', help_text='Flag to be set for pulish status', max_length=11),
        ),
        migrations.AlterField(
            model_name='projects',
            name='secondaryNumber',
            field=models.CharField(default='1111111111', help_text='Secondary Number for SOS', max_length=30, verbose_name='Secondary Number'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='vendorContext',
            field=models.CharField(default='Pace Classic', help_text='Name of a Vendor', max_length=100, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='vendorReferenceId',
            field=models.CharField(default='1', help_text='Id of a Vendor', max_length=100, verbose_name='Vendor Id'),
        ),
    ]
