# Generated by Django 3.0.4 on 2021-10-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_auto_20211019_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='primaryNumber',
            field=models.CharField(blank=True, default=None, help_text='Primary Number for SOS', max_length=30, null=True, verbose_name='Primary Number'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectNature',
            field=models.CharField(default=None, help_text='Natures of a projects', max_length=100, verbose_name='Projects Natures'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectPhase',
            field=models.CharField(default=None, help_text='Phases of a projects', max_length=100, verbose_name='Projects Phases'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='publish',
            field=models.BooleanField(default=None, help_text='Flag to be set for pulish status', max_length=11),
        ),
        migrations.AlterField(
            model_name='projects',
            name='secondaryNumber',
            field=models.CharField(blank=True, default=None, help_text='Secondary Number for SOS', max_length=30, null=True, verbose_name='Secondary Number'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='vendorContext',
            field=models.CharField(default=None, help_text='Name of a Vendor', max_length=100, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='vendorReferenceId',
            field=models.CharField(default=None, help_text='Id of a Vendor', max_length=100, verbose_name='Vendor Id'),
        ),
    ]
