# Generated by Django 3.0.4 on 2021-11-10 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0011_auto_20211026_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectStructureIds', models.CharField(default='*', help_text='project structureIds', max_length=50, verbose_name='Project StructureIds')),
                ('disciplineId', models.BigIntegerField(default=0, help_text='discipline Id details', verbose_name='discipline Id')),
                ('status', models.BooleanField(default=True, help_text='Status of subscription')),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('createdBy', models.BigIntegerField(blank=True, default=None, help_text='User ID who creates', null=True)),
                ('updatedBy', models.BigIntegerField(blank=True, default=None, help_text='UserID who updates', null=True)),
                ('fkCompanyId', models.ForeignKey(help_text='company details', on_delete=django.db.models.deletion.CASCADE, to='companies.Companies', verbose_name='Company')),
                ('fkProjectId', models.ForeignKey(help_text='Projects details', on_delete=django.db.models.deletion.CASCADE, to='companies.Projects', verbose_name='Project ID')),
                ('fkUserId', models.ForeignKey(help_text='department assgin to User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
    ]
