# Generated by Django 3.0.4 on 2021-11-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_projectacl'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstructures',
            name='structureCode',
            field=models.CharField(blank=True, help_text='project structure code', max_length=100, null=True, verbose_name='project structure code'),
        ),
        migrations.AddField(
            model_name='projectstructures',
            name='vendorContext',
            field=models.CharField(blank=True, default=None, help_text='Name of a Vendor', max_length=100, null=True, verbose_name='Vendor Name'),
        ),
        migrations.AddField(
            model_name='projectstructures',
            name='vendorReferenceId',
            field=models.CharField(blank=True, default=None, help_text='Id of a Vendor', max_length=100, null=True, verbose_name='Vendor Id'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='vendorContext',
            field=models.CharField(blank=True, default=None, help_text='Name of a Vendor', max_length=100, null=True, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='vendorReferenceId',
            field=models.CharField(blank=True, default=None, help_text='Id of a Vendor', max_length=100, null=True, verbose_name='Vendor Id'),
        ),
    ]
