# Generated by Django 3.0.4 on 2022-08-22 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0013_auto_20211115_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectacl',
            name='fkUserId',
            field=models.ForeignKey(help_text='User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='projectstructures',
            name='fkCompanyId',
            field=models.ForeignKey(blank=True, default=None, help_text='company details', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Companies', verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='structures',
            name='fkCompanyId',
            field=models.ForeignKey(blank=True, default=None, help_text='company details', null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Companies', verbose_name='Company ID'),
        ),
    ]
