# Generated by Django 3.0.4 on 2021-07-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VersionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('osType', models.CharField(help_text='Please enter OS type', max_length=75, null=True, verbose_name='OS Type')),
                ('VersionInfo', models.CharField(help_text='Please enter OS type', max_length=75, null=True, verbose_name='Versions Type')),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], help_text='Status of notifications', max_length=11)),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('createdBy', models.IntegerField(blank=True, default=None, help_text='User ID who creates', null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('updatedBy', models.IntegerField(blank=True, default=None, help_text='UserID who updates', null=True)),
            ],
            options={
                'verbose_name_plural': 'Versions Types',
            },
        ),
    ]
