# Generated by Django 3.0.4 on 2021-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0003_auto_20210803_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceregistry',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive')], default='active', help_text='Status of notifications', max_length=11),
        ),
    ]
