# Generated by Django 3.0.4 on 2021-08-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0006_auto_20210804_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppliaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appName', models.CharField(help_text='Please enter OS type', max_length=75, null=True, verbose_name='Application Names')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', help_text='Status of mobile apps', max_length=11)),
                ('createdAt', models.DateTimeField(auto_now_add=True, help_text='created date')),
                ('createdBy', models.IntegerField(blank=True, default=None, help_text='User ID who creates', null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, help_text='updated date')),
                ('updatedBy', models.IntegerField(blank=True, default=None, help_text='UserID who updates', null=True)),
            ],
            options={
                'verbose_name_plural': 'Mobile Applications',
                'db_table': 'mobileAppliaction',
            },
        ),
        migrations.AlterModelOptions(
            name='deviceregistry',
            options={'verbose_name_plural': 'Device Registry'},
        ),
        migrations.RenameField(
            model_name='versiontype',
            old_name='VersionInfo',
            new_name='versionInfo',
        ),
        migrations.AlterField(
            model_name='versiontype',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', help_text='Status of device', max_length=11),
        ),
        migrations.AlterModelTable(
            name='deviceregistry',
            table='deviceRegistry',
        ),
        migrations.AlterModelTable(
            name='versiontype',
            table='versions',
        ),
        migrations.AddField(
            model_name='versiontype',
            name='fkMobileApp',
            field=models.ForeignKey(default=None, help_text='App details', null=True, on_delete=django.db.models.deletion.CASCADE, to='versions.MobileAppliaction', verbose_name='Mobile Application'),
        ),
    ]
