# Generated by Django 3.0.4 on 2021-08-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0007_auto_20210804_0734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceRegistry',
        ),
    ]
