# Generated by Django 3.0.4 on 2021-08-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0008_delete_deviceregistry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versiontype',
            old_name='versionInfo',
            new_name='versioninfo',
        ),
    ]
