# Generated by Django 3.0.4 on 2021-08-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0010_auto_20210804_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versiontype',
            options={'verbose_name_plural': 'Version Types'},
        ),
    ]
