# Generated by Django 3.0.4 on 2021-08-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0011_auto_20210804_1056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mobileappliaction',
            table='mobile_appliaction',
        ),
        migrations.AlterModelTable(
            name='versiontype',
            table='version_type',
        ),
    ]
