# Generated by Django 3.0.4 on 2021-10-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0013_auto_20210805_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='versiontype',
            name='versionCode',
            field=models.IntegerField(blank=True, default=None, help_text='Version Code', max_length=11, null=True),
        ),
    ]
