# Generated by Django 3.0.4 on 2021-10-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versions', '0014_versiontype_versioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiontype',
            name='versionCode',
            field=models.IntegerField(blank=True, default=None, help_text='Version Code', null=True),
        ),
    ]
